apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-api
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: platform-api

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s